import { NextResponse } from "next/server";

// Sample EPL match data (matching the main endpoint)
const mockMatches: Record<string, any> = {
  match_001: {
    id: "match_001",
    homeTeam: {
      id: "1",
      name: "Manchester United",
      shortName: "MAN",
      logo: "https://via.placeholder.com/40?text=MAN",
    },
    awayTeam: {
      id: "2",
      name: "Liverpool",
      shortName: "LIV",
      logo: "https://via.placeholder.com/40?text=LIV",
    },
    homeScore: 2,
    awayScore: 1,
    minute: 35,
    status: "FIRST_HALF",
    startTime: new Date().toISOString(),
    venue: "Old Trafford",
    round: 28,
    possession: { home: 55, away: 45 },
    shots: { home: 8, away: 5 },
    shotsOnTarget: { home: 4, away: 2 },
    corners: { home: 3, away: 1 },
    fouls: { home: 8, away: 10 },
    yellowCards: { home: 1, away: 2 },
    redCards: { home: 0, away: 0 },
    events: [
      {
        id: "evt_001",
        type: "GOAL",
        minute: 12,
        team: "home",
        player: "Bruno Fernandes",
        assistPlayer: "Marcus Rashford",
        description: "Goal! Bruno Fernandes scores",
        timestamp: new Date(Date.now() - 1380000).toISOString(),
      },
      {
        id: "evt_002",
        type: "GOAL",
        minute: 28,
        team: "home",
        player: "Marcus Rashford",
        description: "Goal! Marcus Rashford scores",
        timestamp: new Date(Date.now() - 420000).toISOString(),
      },
      {
        id: "evt_003",
        type: "YELLOW_CARD",
        minute: 15,
        team: "away",
        player: "Mo Salah",
        description: "Yellow card for excessive celebration",
        timestamp: new Date(Date.now() - 1200000).toISOString(),
      },
      {
        id: "evt_004",
        type: "GOAL",
        minute: 22,
        team: "away",
        player: "Mo Salah",
        assistPlayer: "Sadio Mané",
        description: "Goal! Mo Salah scores",
        timestamp: new Date(Date.now() - 780000).toISOString(),
      },
    ],
    statistics: {
      possession: { home: 55, away: 45 },
      shots: { home: 8, away: 5 },
      shotsOnTarget: { home: 4, away: 2 },
      corners: { home: 3, away: 1 },
      fouls: { home: 8, away: 10 },
      yellowCards: { home: 1, away: 2 },
      redCards: { home: 0, away: 0 },
    },
  },
  match_002: {
    id: "match_002",
    homeTeam: {
      id: "3",
      name: "Chelsea",
      shortName: "CHE",
      logo: "https://via.placeholder.com/40?text=CHE",
    },
    awayTeam: {
      id: "4",
      name: "Arsenal",
      shortName: "ARS",
      logo: "https://via.placeholder.com/40?text=ARS",
    },
    homeScore: 1,
    awayScore: 1,
    minute: 62,
    status: "SECOND_HALF",
    startTime: new Date(Date.now() - 3600000).toISOString(),
    venue: "Stamford Bridge",
    round: 28,
    possession: { home: 48, away: 52 },
    shots: { home: 10, away: 9 },
    shotsOnTarget: { home: 5, away: 4 },
    corners: { home: 4, away: 3 },
    fouls: { home: 12, away: 11 },
    yellowCards: { home: 2, away: 1 },
    redCards: { home: 0, away: 0 },
    events: [
      {
        id: "evt_201",
        type: "GOAL",
        minute: 18,
        team: "home",
        player: "Cole Palmer",
        assistPlayer: "Moises Caicedo",
        description: "Goal! Cole Palmer scores",
        timestamp: new Date(Date.now() - 3180000).toISOString(),
      },
      {
        id: "evt_202",
        type: "YELLOW_CARD",
        minute: 25,
        team: "away",
        player: "Bukayo Saka",
        description: "Yellow card for rough play",
        timestamp: new Date(Date.now() - 2700000).toISOString(),
      },
      {
        id: "evt_203",
        type: "GOAL",
        minute: 45,
        team: "away",
        player: "Kai Havertz",
        assistPlayer: "Bukayo Saka",
        description: "Goal! Kai Havertz scores",
        timestamp: new Date(Date.now() - 1260000).toISOString(),
      },
      {
        id: "evt_204",
        type: "SHOT",
        minute: 58,
        team: "home",
        player: "Enzo Fernandez",
        description: "Shot misses",
        timestamp: new Date(Date.now() - 240000).toISOString(),
      },
    ],
    statistics: {
      possession: { home: 48, away: 52 },
      shots: { home: 10, away: 9 },
      shotsOnTarget: { home: 5, away: 4 },
      corners: { home: 4, away: 3 },
      fouls: { home: 12, away: 11 },
      yellowCards: { home: 2, away: 1 },
      redCards: { home: 0, away: 0 },
    },
  },
  match_003: {
    id: "match_003",
    homeTeam: {
      id: "5",
      name: "Manchester City",
      shortName: "MCI",
      logo: "https://via.placeholder.com/40?text=MCI",
    },
    awayTeam: {
      id: "6",
      name: "Tottenham",
      shortName: "TOT",
      logo: "https://via.placeholder.com/40?text=TOT",
    },
    homeScore: 3,
    awayScore: 0,
    minute: 90,
    status: "FULL_TIME",
    startTime: new Date(Date.now() - 7200000).toISOString(),
    venue: "Etihad Stadium",
    round: 28,
    possession: { home: 62, away: 38 },
    shots: { home: 18, away: 4 },
    shotsOnTarget: { home: 8, away: 1 },
    corners: { home: 7, away: 1 },
    fouls: { home: 6, away: 14 },
    yellowCards: { home: 0, away: 2 },
    redCards: { home: 0, away: 0 },
    events: [
      {
        id: "evt_301",
        type: "GOAL",
        minute: 8,
        team: "home",
        player: "Erling Haaland",
        assistPlayer: "Jack Grealish",
        description: "Goal! Erling Haaland scores",
        timestamp: new Date(Date.now() - 6912000).toISOString(),
      },
      {
        id: "evt_302",
        type: "YELLOW_CARD",
        minute: 22,
        team: "away",
        player: "Rodrigo Bentancur",
        description: "Yellow card for harsh tackle",
        timestamp: new Date(Date.now() - 6216000).toISOString(),
      },
      {
        id: "evt_303",
        type: "GOAL",
        minute: 35,
        team: "home",
        player: "Julian Alvarez",
        assistPlayer: "Phil Foden",
        description: "Goal! Julian Alvarez scores",
        timestamp: new Date(Date.now() - 5460000).toISOString(),
      },
      {
        id: "evt_304",
        type: "GOAL",
        minute: 67,
        team: "home",
        player: "Phil Foden",
        description: "Goal! Phil Foden scores",
        timestamp: new Date(Date.now() - 3180000).toISOString(),
      },
      {
        id: "evt_305",
        type: "YELLOW_CARD",
        minute: 78,
        team: "away",
        player: "Maddison",
        description: "Yellow card for dissent",
        timestamp: new Date(Date.now() - 720000).toISOString(),
      },
    ],
    statistics: {
      possession: { home: 62, away: 38 },
      shots: { home: 18, away: 4 },
      shotsOnTarget: { home: 8, away: 1 },
      corners: { home: 7, away: 1 },
      fouls: { home: 6, away: 14 },
      yellowCards: { home: 0, away: 2 },
      redCards: { home: 0, away: 0 },
    },
  },
  match_004: {
    id: "match_004",
    homeTeam: { id: "7", name: "Brighton", shortName: "BHA", logo: "https://via.placeholder.com/40?text=BHA" },
    awayTeam: { id: "8", name: "Aston Villa", shortName: "AVL", logo: "https://via.placeholder.com/40?text=AVL" },
    homeScore: 2,
    awayScore: 2,
    minute: 90,
    status: "FULL_TIME",
    startTime: new Date(Date.now() - 10800000).toISOString(),
    venue: "Amex Stadium",
    round: 28,
    possession: { home: 51, away: 49 },
    shots: { home: 12, away: 10 },
    shotsOnTarget: { home: 6, away: 5 },
    corners: { home: 5, away: 4 },
    fouls: { home: 10, away: 9 },
    yellowCards: { home: 1, away: 1 },
    redCards: { home: 0, away: 0 },
    events: [],
    statistics: { possession: { home: 51, away: 49 }, shots: { home: 12, away: 10 }, shotsOnTarget: { home: 6, away: 5 }, corners: { home: 5, away: 4 }, fouls: { home: 10, away: 9 }, yellowCards: { home: 1, away: 1 }, redCards: { home: 0, away: 0 } },
  },
  match_005: {
    id: "match_005",
    homeTeam: { id: "9", name: "Newcastle", shortName: "NEW", logo: "https://via.placeholder.com/40?text=NEW" },
    awayTeam: { id: "10", name: "Brentford", shortName: "BRE", logo: "https://via.placeholder.com/40?text=BRE" },
    homeScore: 1,
    awayScore: 0,
    minute: 90,
    status: "FULL_TIME",
    startTime: new Date(Date.now() - 14400000).toISOString(),
    venue: "St James Park",
    round: 28,
    possession: { home: 58, away: 42 },
    shots: { home: 14, away: 6 },
    shotsOnTarget: { home: 7, away: 2 },
    corners: { home: 6, away: 2 },
    fouls: { home: 8, away: 12 },
    yellowCards: { home: 0, away: 2 },
    redCards: { home: 0, away: 0 },
    events: [],
    statistics: { possession: { home: 58, away: 42 }, shots: { home: 14, away: 6 }, shotsOnTarget: { home: 7, away: 2 }, corners: { home: 6, away: 2 }, fouls: { home: 8, away: 12 }, yellowCards: { home: 0, away: 2 }, redCards: { home: 0, away: 0 } },
  },
  match_006: {
    id: "match_006",
    homeTeam: { id: "11", name: "West Ham", shortName: "WHU", logo: "https://via.placeholder.com/40?text=WHU" },
    awayTeam: { id: "12", name: "Nottingham Forest", shortName: "NFO", logo: "https://via.placeholder.com/40?text=NFO" },
    homeScore: 0,
    awayScore: 0,
    minute: 0,
    status: "NOT_STARTED",
    startTime: new Date(Date.now() + 3600000).toISOString(),
    venue: "London Stadium",
    round: 28,
    possession: { home: 0, away: 0 },
    shots: { home: 0, away: 0 },
    shotsOnTarget: { home: 0, away: 0 },
    corners: { home: 0, away: 0 },
    fouls: { home: 0, away: 0 },
    yellowCards: { home: 0, away: 0 },
    redCards: { home: 0, away: 0 },
    events: [],
    statistics: { possession: { home: 0, away: 0 }, shots: { home: 0, away: 0 }, shotsOnTarget: { home: 0, away: 0 }, corners: { home: 0, away: 0 }, fouls: { home: 0, away: 0 }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  },
  match_007: {
    id: "match_007",
    homeTeam: { id: "13", name: "Fulham", shortName: "FUL", logo: "https://via.placeholder.com/40?text=FUL" },
    awayTeam: { id: "14", name: "Bournemouth", shortName: "BOU", logo: "https://via.placeholder.com/40?text=BOU" },
    homeScore: 0,
    awayScore: 0,
    minute: 0,
    status: "NOT_STARTED",
    startTime: new Date(Date.now() + 7200000).toISOString(),
    venue: "Craven Cottage",
    round: 28,
    possession: { home: 0, away: 0 },
    shots: { home: 0, away: 0 },
    shotsOnTarget: { home: 0, away: 0 },
    corners: { home: 0, away: 0 },
    fouls: { home: 0, away: 0 },
    yellowCards: { home: 0, away: 0 },
    redCards: { home: 0, away: 0 },
    events: [],
    statistics: { possession: { home: 0, away: 0 }, shots: { home: 0, away: 0 }, shotsOnTarget: { home: 0, away: 0 }, corners: { home: 0, away: 0 }, fouls: { home: 0, away: 0 }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  },
  match_008: {
    id: "match_008",
    homeTeam: { id: "15", name: "Everton", shortName: "EVE", logo: "https://via.placeholder.com/40?text=EVE" },
    awayTeam: { id: "16", name: "Wolverhampton", shortName: "WOL", logo: "https://via.placeholder.com/40?text=WOL" },
    homeScore: 0,
    awayScore: 0,
    minute: 0,
    status: "NOT_STARTED",
    startTime: new Date(Date.now() + 10800000).toISOString(),
    venue: "Goodison Park",
    round: 28,
    possession: { home: 0, away: 0 },
    shots: { home: 0, away: 0 },
    shotsOnTarget: { home: 0, away: 0 },
    corners: { home: 0, away: 0 },
    fouls: { home: 0, away: 0 },
    yellowCards: { home: 0, away: 0 },
    redCards: { home: 0, away: 0 },
    events: [],
    statistics: { possession: { home: 0, away: 0 }, shots: { home: 0, away: 0 }, shotsOnTarget: { home: 0, away: 0 }, corners: { home: 0, away: 0 }, fouls: { home: 0, away: 0 }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  },
  match_009: {
    id: "match_009",
    homeTeam: { id: "17", name: "Crystal Palace", shortName: "CRY", logo: "https://via.placeholder.com/40?text=CRY" },
    awayTeam: { id: "18", name: "Ipswich Town", shortName: "IPS", logo: "https://via.placeholder.com/40?text=IPS" },
    homeScore: 0,
    awayScore: 0,
    minute: 0,
    status: "NOT_STARTED",
    startTime: new Date(Date.now() + 14400000).toISOString(),
    venue: "Selhurst Park",
    round: 28,
    possession: { home: 0, away: 0 },
    shots: { home: 0, away: 0 },
    shotsOnTarget: { home: 0, away: 0 },
    corners: { home: 0, away: 0 },
    fouls: { home: 0, away: 0 },
    yellowCards: { home: 0, away: 0 },
    redCards: { home: 0, away: 0 },
    events: [],
    statistics: { possession: { home: 0, away: 0 }, shots: { home: 0, away: 0 }, shotsOnTarget: { home: 0, away: 0 }, corners: { home: 0, away: 0 }, fouls: { home: 0, away: 0 }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  },
  match_010: {
    id: "match_010",
    homeTeam: { id: "19", name: "Luton Town", shortName: "LUT", logo: "https://via.placeholder.com/40?text=LUT" },
    awayTeam: { id: "20", name: "Leicester City", shortName: "LEI", logo: "https://via.placeholder.com/40?text=LEI" },
    homeScore: 0,
    awayScore: 0,
    minute: 0,
    status: "NOT_STARTED",
    startTime: new Date(Date.now() + 18000000).toISOString(),
    venue: "Kenilworth Road",
    round: 28,
    possession: { home: 0, away: 0 },
    shots: { home: 0, away: 0 },
    shotsOnTarget: { home: 0, away: 0 },
    corners: { home: 0, away: 0 },
    fouls: { home: 0, away: 0 },
    yellowCards: { home: 0, away: 0 },
    redCards: { home: 0, away: 0 },
    events: [],
    statistics: { possession: { home: 0, away: 0 }, shots: { home: 0, away: 0 }, shotsOnTarget: { home: 0, away: 0 }, corners: { home: 0, away: 0 }, fouls: { home: 0, away: 0 }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  },
  match_011: {
    id: "match_011",
    homeTeam: { id: "21", name: "Southampton", shortName: "SOU", logo: "https://via.placeholder.com/40?text=SOU" },
    awayTeam: { id: "1", name: "Manchester United", shortName: "MAN", logo: "https://via.placeholder.com/40?text=MAN" },
    homeScore: 0,
    awayScore: 0,
    minute: 0,
    status: "NOT_STARTED",
    startTime: new Date(Date.now() + 21600000).toISOString(),
    venue: "St Mary's Stadium",
    round: 28,
    possession: { home: 0, away: 0 },
    shots: { home: 0, away: 0 },
    shotsOnTarget: { home: 0, away: 0 },
    corners: { home: 0, away: 0 },
    fouls: { home: 0, away: 0 },
    yellowCards: { home: 0, away: 0 },
    redCards: { home: 0, away: 0 },
    events: [],
    statistics: { possession: { home: 0, away: 0 }, shots: { home: 0, away: 0 }, shotsOnTarget: { home: 0, away: 0 }, corners: { home: 0, away: 0 }, fouls: { home: 0, away: 0 }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  },
  match_012: {
    id: "match_012",
    homeTeam: { id: "22", name: "Coventry City", shortName: "COV", logo: "https://via.placeholder.com/40?text=COV" },
    awayTeam: { id: "23", name: "Burnley", shortName: "BUR", logo: "https://via.placeholder.com/40?text=BUR" },
    homeScore: 0,
    awayScore: 0,
    minute: 0,
    status: "NOT_STARTED",
    startTime: new Date(Date.now() + 86400000).toISOString(),
    venue: "Coventry Stadium",
    round: 28,
    possession: { home: 0, away: 0 },
    shots: { home: 0, away: 0 },
    shotsOnTarget: { home: 0, away: 0 },
    corners: { home: 0, away: 0 },
    fouls: { home: 0, away: 0 },
    yellowCards: { home: 0, away: 0 },
    redCards: { home: 0, away: 0 },
    events: [],
    statistics: { possession: { home: 0, away: 0 }, shots: { home: 0, away: 0 }, shotsOnTarget: { home: 0, away: 0 }, corners: { home: 0, away: 0 }, fouls: { home: 0, away: 0 }, yellowCards: { home: 0, away: 0 }, redCards: { home: 0, away: 0 } },
  },
};

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;

    const match = mockMatches[id];

    if (!match) {
      return NextResponse.json(
        { success: false, error: "Match not found" },
        { status: 404 }
      );
    }

    return NextResponse.json(
      {
        success: true,
        data: match,
      },
      { status: 200 }
    );
  } catch (error) {
    console.error("Error fetching match:", error);
    return NextResponse.json(
      { success: false, error: "Failed to fetch match" },
      { status: 500 }
    );
  }
}
